### ISSUE TITLE
Uncaught ReferenceError: DateTimeShortcuts is not defined

### ISSUE THREAD

**Issue by jttttttttttttt** [assem-ch/django-jet-reboot#79]
`
django==4.1.7
django-jet-reboot==1.3.3
django-admin-rangefilter==0.9.0
`
If I uninstall django-admin-rangefilter, I will occur error:  cant find jet.filters.DateRangeFilter.

However i use django-admin-rangefilter or django-jet-reboot, like
`
from rangefilter.filters import DateRangeFilter
or
from jet.filters import DateRangeFilter
`

will occur error:
`
Uncaught ReferenceError: DateTimeShortcuts is not defined
    at Array.<anonymous> ((index):283:17)
    at fire (jquery.js:3500:31)
    at Object.fireWith [as resolveWith] (jquery.js:3630:7)
    at Object.<anonymous> (jquery.js:4013:15)
    at fire (jquery.js:3500:31)
    at Object.fireWith [as resolveWith] (jquery.js:3630:7)
    at done (jquery.js:9796:14)
    at XMLHttpRequest.<anonymous> (jquery.js:10057:9)
`

**Comment by jttttttttttttt** [comment]
This is test in  error static Path....
